AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pet Store Rest API Service
Resources:
  DakobedServerlessApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-pipeline/b08c7545ed198f4160a4f943a24f14a8
  PostPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostPetFunction
      Runtime: python3.6
      Handler: function.handler
      CodeUri: s3://dakobed-serverless-pipeline/96f6ab16c8f819d617b611d12008806f
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedServerlessApiGateway
            Path: /pet
            Method: POST
      Policies:
      - AWSLambdaBasicExecutionRole
  GetGuitarSetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetGuitarSetFunction
      Runtime: python3.6
      Handler: function.lambda_handler
      CodeUri: s3://dakobed-serverless-pipeline/e26c39cae36d201d1072a77a09a8df2f
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedServerlessApiGateway
            Path: /guitarset
            Method: GET
      Policies:
      - AWSLambdaBasicExecutionRole
      - DynamoDBReadPolicy:
          TableName: Dakobed-GuitarSet
  SnotelQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - DynamoDBCrudPolicy:
          TableName: Snotel
      CodeUri: s3://dakobed-serverless-pipeline/3981a697c837e01d2b15925072315d74
      Handler: snotel_lambda.lambda_handler
      Runtime: python3.7
      Events:
        SnotelApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedServerlessApiGateway
            Path: /snotel
            Method: GET
  GetPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetPetFunction
      Runtime: python3.6
      Handler: function.handler
      CodeUri: s3://dakobed-serverless-pipeline/0f76bf03c9f345f531d91d8d9c2c5f6e
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedServerlessApiGateway
            Path: /pet/{petId}
            Method: GET
      Policies:
      - AWSLambdaBasicExecutionRole
