AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pet Store Rest API Service
Resources:
  DakobedApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-pipeline/fbdf54de3954910cbcce96fc720500c8
  PostPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostPetFunction
      Runtime: python3.6
      Handler: function.handler
      CodeUri: s3://dakobed-serverless-pipeline/19c0d7c6ac770242e4214ae99db19eb3
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedApiGateway
            Path: /pet
            Method: POST
      Policies:
      - AWSLambdaBasicExecutionRole
  GetPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetPetFunction
      Runtime: python3.6
      Handler: function.handler
      CodeUri: s3://dakobed-serverless-pipeline/7880834342f681df5712729091e4af3e
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedApiGateway
            Path: /pet/{petId}
            Method: GET
      Policies:
      - AWSLambdaBasicExecutionRole
  SnotelQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SnotelQueryFunction
      Policies:
      - DynamoDBCrudPolicy:
          TableName: Snotel
      CodeUri: s3://dakobed-serverless-pipeline/71da5c4eb75392468dbfe55eb0ddf6fc
      Handler: snotel_lambda.lambda_handler
      Runtime: python3.7
      Events:
        SnotelApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedApiGateway
            Path: /snotel
            Method: GET
