AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service
Resources:
  DakobedApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-pipeline/1d7d625299830000194c77431c8257b7
      BinaryMediaTypes:
      - application/audio
  GuitarsetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GuitarsetFunction
      Policies:
      - DynamoDBReadPolicy:
          TableName: DakobedGuitarSet
      CodeUri: s3://dakobed-serverless-pipeline/69303d62315c49e9750a4201504f1ede
      Handler: handler.lambda_handler
      Runtime: python3.7
      Events:
        GuitarsetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedApiGateway
            Path: /guitarset
            Method: GET
