AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service
Resources:
  DakobedApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-pipeline/a8a65b2093f01db50bea538f8b5ac7ad
      BinaryMediaTypes:
      - application/audio
  DakobedModelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: s3://dakobed-serverless-pipeline/1623a7b39f64cce8115c623cd82aee23
      CompatibleRuntimes:
      - python3.6
    Metadata:
      BuildMethod: python3.6
  TranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranscriptionFunction
      Runtime: python3.6
      Handler: handler.lambda_handler
      CodeUri: s3://dakobed-serverless-pipeline/d5a2bb93d8b91563b3b28dc003887de5
      Events:
        TranscriptionApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedApiGateway
            Path: /transcription/
            Method: post
      Policies:
      - AWSLambdaBasicExecutionRole
      - DynamoDBReadPolicy:
          TableName: DakobedGuitarTranscriptions
      Layers:
      - arn:aws:lambda:us-west-2:347034527139:layer:tf_1_11_keras:1
      - Ref: DakobedModelLayer
