AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service
Resources:
  DakobedApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-pipeline/5ca99988e394193b95d1fca6044a280a
      BinaryMediaTypes:
      - application/audio
  DakobedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: s3://dakobed-serverless-pipeline/d71ac367abf104f765cb3457f26334f4
      CompatibleRuntimes:
      - python3.6
    Metadata:
      BuildMethod: python3.6
  LayerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LayerFunction
      Runtime: python3.6
      Handler: lambda_handler.handler
      CodeUri: s3://dakobed-serverless-pipeline/bf1670bf1ccbf3c41e28e973a53634a3
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: DakobedApiGateway
            Path: /transcription/{transcriptionId}
            Method: GET
      Policies:
      - AWSLambdaBasicExecutionRole
      - DynamoDBReadPolicy:
          TableName: DakobedTranscriptions
      Layers:
      - Ref: DakobedLayer
