AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service


Resources:
  DakobedTranscriptionsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ./swagger.yaml
      BinaryMediaTypes:
        - application/audio

  DakobedModelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: model-layer.zip
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: python3.6

  TranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TranscriptionFunction
      Runtime: python3.6
      Handler: handler.lambda_handler
      CodeUri: ./transcriptions/
      MemorySize: 512
      Timeout: 30
      Events:
        TranscriptionApi:
          Type: Api
          Properties:
            RestApiId: !Ref DakobedTranscriptionsApi
            Path: /transcription/
            Method: post
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedGuitarTranscriptions
      Layers:
        - arn:aws:lambda:us-west-2:347034527139:layer:tf_1_11_keras:1
        - !Ref DakobedModelLayer


  GetTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetTranscriptionFunction
      Runtime: python3.6
      Handler: function.handler
      CodeUri: ./getTranscription/
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref DakobedTranscriptionsApi
            Path: /transcription/{transcriptionId}
            Method: GET
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedTranscriptions

  LaunchEC2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LaunchEC2Function
#      Role: arn:aws:iam::710339184759:role/Lamda-LaunchEC2
      Runtime: python3.6
      Handler: handler.lambda_handler
      CodeUri: ./launchEC2/
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:710339184759:TransformQueue
            BatchSize: 10
            Enabled: false
      Policies:
        - arn:aws:iam::710339184759:policy/LambdaLaunchEC2Policy
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: DakobedTranscriptions

  StopEC2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StopEC2Function
      Runtime: python3.6
      Handler: handler.lambda_handler
      CodeUri: ./stopEC2/
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:710339184759:TransformQueue
            BatchSize: 10
            Enabled: false
      Policies:
        - arn:aws:iam::710339184759:policy/LambdaLaunchEC2Policy
        - AWSLambdaBasicExecutionRole







#
#
#
#  GuitarsetFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      FunctionName: GuitarsetFunction
#      Policies:
#        - DynamoDBReadPolicy:
#            TableName: DakobedGuitarSet
#      CodeUri: guitarset/
#      Handler: handler.lambda_handler
#      Runtime: python3.7
#      Events:
#        GuitarsetApi:
#          Type: Api
#          Properties:
#            RestApiId: !Ref DakobedApiGateway
#            Path: /guitarset
#            Method: GET



